- name: Configure and deploy fullstack application
  hosts: all
  become: true
  roles: 
    - common:
      tags: monitoring
    - role: app
      tags: application
    - role: monitoring
      tags: monitoring