name: Ansible Monitoring Deploy

on:
  workflow_dispatch: {}

jobs:
  ansible-monitoring:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Generate Inventory
        run: |
          PUBLIC_IP=$(terraform output -raw public_ip)
          echo "[app]" > ansible/inventory
          echo "${PUBLIC_IP} ansible_user=ubuntu ansible_ssh_private_key_file=/path/to/key.pem" >> ansible/inventory

      - name: Run Ansible Playbook for Monitoring
        run: ansible-playbook -i ansible/inventory ansible/playbook.yml --tags "monitoring"
