name: CD Application

on:
  push:
    branches: [ "deployment" ]

jobs:
  app-cd:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Ansible
        run: sudo apt-get update && sudo apt-get install -y ansible

      - name: Deploy Application Stack
        run: ansible-playbook -i ansible/inventory ansible/playbook.yml --tags "application"
