name: CI Application

on:
  push:
    branches: [ "integration" ]

jobs:
  app-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Docker Login
        run: echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin

      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:latest

      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:latest .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:latest

      - name: Update docker-compose.yml
        run: |
          sed -i "s|image: .*/frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:latest|" docker-compose.yml
          sed -i "s|image: .*/backend:.*|image: ${{ secrets.DOCKER_USERNAME }}/backend:latest|" docker-compose.yml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "Update docker-compose images"
          git push
