name: CI Application

on:
  push:
    branches: [ "integration" ]

permissions:
  contents: write

jobs:
  app-ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: true

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Frontend
        run: |
          cd frontend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_number }}

      - name: Build and Push Backend
        run: |
          cd backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_number }} .
          docker push ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_number }}

      - name: Update docker-compose.yml
        run: |
          sed -i "s|image: .*/frontend:.*|image: ${{ secrets.DOCKER_USERNAME }}/frontend:${{ github.run_number }}|" docker-compose.yml
          sed -i "s|image: .*/backend:.*|image: ${{ secrets.DOCKER_USERNAME }}/backend:${{ github.run_number }}|" docker-compose.yml
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add docker-compose.yml
          git commit -m "Update docker-compose images"
          git push
