name: Terraform Apply

on:
  pull_request:
    branches: [ "infra_main" ]
    types: [closed]

jobs:
  terraform-apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Write PEM file
        run: |
          cd terraform
          echo "${{ secrets.NGINIX_KEY }}" > nginix.pem 
          chmod 600 nginix.pem

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Output
        id: tf_output
        run: terraform output -json > tf_outputs.json
