name: Terraform Apply

on:
  pull_request:
    branches: [ "infra_main" ]
    types: [closed]

jobs:
  terraform-apply:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with: 
          persist-credentials: true

      - name: Create vars file
        run: |
          mkdir -p ansible/vars
          echo "docker_hub_username: \"${{ secrets.DOCKER_USERNAME }}\"" > ansible/vars/docker_hub.yml
          echo "docker_hub_password: \"${{ secrets.DOCKER_PASSWORD }}\"" >> ansible/vars/docker_hub.yml

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Write PEM file
        run: |
          cd terraform
          echo "${{ secrets.NGINIX_KEY }}" > nginix.pem 
          chmod 600 nginix.pem

      - name: Configure AWS Credentials
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Terraform Apply
        run: |
          cd terraform
          terraform apply -auto-approve

      - name: Terraform Output
        id: tf_output
        run: terraform output -json > tf_outputs.json
