name: Terraform Plan and Cost

on:
  pull_request:
    branches: [ "infra_main" ]

env:
  INFRACOST_API_KEY: ${{ secrets.INFRACOST_API_KEY }}

jobs:
  terraform-plan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.3.0

      - name: Terraform Init
        run: |
          cd terraform
          terraform init

      - name: Write PEM file
        run: |
          cd terraform
          echo "${{ secrets.NGINIX_KEY }}" > nginix.pem 
          chmod 600 nginix.pem

      - name: Configure AWS Credentials
        run: |
          mkdir ~/.aws
          echo "[default]" > ~/.aws/credentials
          echo "aws_access_key_id=${{ secrets.ACCESS_KEY }}" >> ~/.aws/credentials
          echo "aws_secret_access_key=${{ secrets.SECRET_ACCESS_KEY }}" >> ~/.aws/credentials

      - name: Terraform Plan
        id: plan
        run: |
          cd terraform
          terraform plan -no-color -out=plan.out

      - name: Setup InfraCost
        uses: infracost/actions/setup@v3
        with:
          api_key: ${{ secrets.INFRACOST_API_KEY }}
      
      # If using InfraCost for cost estimates
      - name: InfraCost Breakdown
        id: infracost
        run: |
          cd terraform
          infracost breakdown --path . --format json --out-file infracost.json
          # Additional steps to format the output can be added here

      - name: Comment on PR with Plan and Cost
        run: |
          infracost comment github --path=/tmp/infracost.json \
          --repo=$GITHUB_REPOSITORY \
          --github-token=${{ github.token }} \
          --pull-request=${{ github.event.pull_request.number }} \
          --behavior=update
